name : Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.14.0.2'
      - run: sudo apt-get install texlive texlive-fonts-extra # Merrieweather
      - run: make
      - uses: ame-yu/action-delete-latest-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     -
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Release notes"
          name: Latest
          tag_name: release
          files: ./pdf/guideline.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
